name: pimdrupal
recipe: drupal10
config:
  via: nginx
  webroot: web
  php: 8.1
  database: mariadb:10.6

services:
  appserver_pimcore:
    type: php:8.0
    via: apache:2.4
    webroot: pimcore/public
    ssl: true
    sslExpose: true
    build_as_root:
      - apt-get update -y
      - apt-get install -y locales-all
  database_pimcore:
    type: mariadb:10.6
    config:
      database_pimcore: .lando-config/pimcore-my.cnf
    creds:
      user: pimcore_db
      password: pimcore_db
      database: pimcore_db
  phpmyadmin:
    type: phpmyadmin
    hosts:
    - database
    - database_pimcore

proxy:
  appserver_pimcore:
    - pimcore-pimdrupal.lndo.site

  phpmyadmin:
    - myadmin-pimdrupal.lndo.site

tooling:
  phpcs:
    service: appserver
    cmd: "/app/vendor/bin/phpcs --standard=Drupal,DrupalPractice"
    options:
    description: Run phpcs for given folder or file.
  pimcore-install:
    service: appserver
    cmd: "/app/pimcore/vendor/bin/pimcore-install \
      --admin-username=admin --admin-password=1234 \
      --mysql-username=pimcore_db --mysql-password=pimcore_db --mysql-database=pimcore_db \
      --mysql-host-socket=database_pimcore --mysql-port=3306 \
      --no-interaction"
    description: Run pimcore-install script.
