name: pimdrupal
recipe: drupal10
config:
  via: nginx
  webroot: web
  php: 8.2
  database: mariadb

services:
  appserver_pimcore:
    type: php:8.2
    via: apache:2.4
    webroot: pimcore/public
    ssl: true
    sslExpose: true
    build_as_root:
      - apt-get update -y
      - apt-get install -y locales-all
      - docker-php-ext-install sockets
      - docker-php-ext-enable sockets
  database_pimcore:
    type: mariadb
    config:
      database: .lando-config/my-pimcore.cnf
    creds:
      user: pimcore_db
      password: pimcore_db
      database: pimcore_db
  phpmyadmin:
    type: phpmyadmin
    hosts:
    - database
    - database_pimcore

proxy:
  appserver_pimcore:
    - pimcore-pimdrupal.lndo.site
  phpmyadmin:
    - myadmin-pimdrupal.lndo.site

tooling:
  phpcs:
    service: appserver
    cmd: "/app/vendor/bin/phpcs --ignore=*/pimcore/* --standard=Drupal,DrupalPractice"
    options:
    description: "Run phpcs for given folder or file."
  pim-console:
    service: appserver_pimcore
    cmd: "cd /app/pimcore/bin/ && php console"
    description: "Run bin/console commands."
  pimcore-install:
    service: appserver_pimcore
    cmd: "cd /app/pimcore/vendor/bin/ && ./pimcore-install \
      --admin-username=admin --admin-password=1234 \
      --mysql-username=pimcore_db --mysql-password=pimcore_db --mysql-database=pimcore_db \
      --mysql-host-socket=database_pimcore --mysql-port=3306 \
      --no-interaction"
    description: "Run pimcore-install script. Drop/Create app database and define admin user credentials (User: admin, Pass: 1234)."
