name: pimdrupal
recipe: drupal10
config:
  via: nginx
  webroot: web
  php: 8.1
  database: mariadb

services:
  phpmyadmin:
    type: phpmyadmin
    hosts:
    - database

tooling:
  phpcs:
    service: appserver
    cmd: "/app/vendor/bin/phpcs --standard=Drupal,DrupalPractice"
    options:
    description: Run phpcs for given folder or file.
