pimcore_data_hub:
    configurations:
        assets:
            general:
                active: true
                type: graphql
                name: assets
                description: ''
                group: ''
                sqlObjectCondition: ''
                modificationDate: 1694089047
                path: null
                createDate: 1693314341
            schema:
                queryEntities: {  }
                mutationEntities: {  }
                specialEntities:
                    document:
                        read: false
                        create: false
                        update: false
                        delete: false
                    document_folder:
                        read: false
                        create: false
                        update: false
                        delete: false
                    asset:
                        read: true
                        create: false
                        update: false
                        delete: false
                    asset_folder:
                        read: true
                        create: false
                        update: false
                        delete: false
                    asset_listing:
                        read: true
                        create: false
                        update: false
                        delete: false
                    object_folder:
                        read: false
                        create: false
                        update: false
                        delete: false
                    translation:
                        read: false
                        create: false
                        update: false
                        delete: false
                    translation_listing:
                        read: false
                        create: false
                        update: false
                        delete: false
            security:
                method: datahub_apikey
                apikey:
                    - 9cbdc521eba20a190c9636f29b8a242f
                skipPermissionCheck: true
                disableIntrospection: false
            workspaces:
                asset: {  }
                document: {  }
                object: {  }
            permissions:
                user: {  }
                role: {  }
